# Generated by Django 3.0 on 2019-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191210_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
