# Generated by Django 3.0 on 2019-12-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191210_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
