# Generated by Django 3.0 on 2019-12-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191210_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='city',
        ),
        migrations.AddField(
            model_name='incident',
            name='city',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.State'),
            preserve_default=False,
        ),
    ]
